// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASL-rKtwTY0jZmFZPxKzccr6Ab2QShevg',
    appId: '1:430524128666:web:5a1a7cd46751bc13f62e23',
    messagingSenderId: '430524128666',
    projectId: 'supernarkt',
    authDomain: 'supernarkt.firebaseapp.com',
    storageBucket: 'supernarkt.firebasestorage.app',
    measurementId: 'G-2C1NM391EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9EZctTDvNAI8fthsN_k8Tej-g67t5GI',
    appId: '1:430524128666:android:672f2f4cad9588eef62e23',
    messagingSenderId: '430524128666',
    projectId: 'supernarkt',
    storageBucket: 'supernarkt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCvNYk3Qb7qYKQnKm_Z7etN7-PPTzJ5M',
    appId: '1:430524128666:ios:dc7cd7d242f80cb3f62e23',
    messagingSenderId: '430524128666',
    projectId: 'supernarkt',
    storageBucket: 'supernarkt.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCvNYk3Qb7qYKQnKm_Z7etN7-PPTzJ5M',
    appId: '1:430524128666:ios:dc7cd7d242f80cb3f62e23',
    messagingSenderId: '430524128666',
    projectId: 'supernarkt',
    storageBucket: 'supernarkt.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASL-rKtwTY0jZmFZPxKzccr6Ab2QShevg',
    appId: '1:430524128666:web:48b4de209d859f97f62e23',
    messagingSenderId: '430524128666',
    projectId: 'supernarkt',
    authDomain: 'supernarkt.firebaseapp.com',
    storageBucket: 'supernarkt.firebasestorage.app',
    measurementId: 'G-47ND7N2H7F',
  );
}
